<?php // markup and images generated by https://realfavicongenerator.net ?>
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo get_template_directory_uri(); ?>/_assets/img/favicon/apple-touch-icon.png?v=20160912">
<link rel="icon" type="image/png" href="<?php echo get_template_directory_uri(); ?>/_assets/img/favicon/favicon-32x32.png?v=20160912" sizes="32x32">
<link rel="icon" type="image/png" href="<?php echo get_template_directory_uri(); ?>/_assets/img/favicon/favicon-16x16.png?v=20160912" sizes="16x16">
<link rel="manifest" href="<?php echo get_template_directory_uri(); ?>/_assets/img/favicon/manifest.json?v=20160912">
<link rel="mask-icon" href="<?php echo get_template_directory_uri(); ?>/_assets/img/favicon/safari-pinned-tab.svg?v=20160912" color="#a51417">
<link rel="shortcut icon" href="<?php echo get_template_directory_uri(); ?>/_assets/img/favicon/favicon.ico?v=20160912">
<meta name="msapplication-config" content="<?php echo get_template_directory_uri(); ?>/_assets/img/favicon/browserconfig.xml?v=20160912">
