<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

acf_add_local_field_group( array(
	'key' => 'group_5b05cc22d2580',
	'title' => 'Spotlight Overlay',
	'fields' => array(
		array(
			'key' => 'field_5b3e5497699dd',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '<a href="https://webtheme.wustl.edu/items/using-the-homepage-spotlight-layout/">See Spotlight layout instructions »</a>',
			'new_lines' => '',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_60c8f58cf8759',
			'label' => 'Show page title in Showcase',
			'name' => 'show_page_title_in_showcase',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5b05cc8b68cf6',
			'label' => 'Content',
			'name' => 'overlay_content',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'5b05cc8d2870e' => array(
					'key' => '5b05cc8d2870e',
					'name' => 'heading',
					'label' => 'Heading',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b05cca968cf7',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b05cd166d47d' => array(
					'key' => '5b05cd166d47d',
					'name' => 'subheading',
					'label' => 'Subheading',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b05ccb968cf8',
							'label' => 'Subheading',
							'name' => 'subheading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b05cd4d6d47e' => array(
					'key' => '5b05cd4d6d47e',
					'name' => 'button',
					'label' => 'Button',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b05ccda68cfb',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b05ccdf68cfc',
							'label' => 'URL',
							'name' => 'url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Element',
			'min' => '',
			'max' => '',
		),
		array(
			'key' => 'field_5b0eace8811ce',
			'label' => 'Color',
			'name' => 'overlay_color',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'red' => 'Red',
				'dark-gray' => 'Dark Gray',
				'turquoise' => 'Turquoise',
				'yellow' => 'Yellow',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'red',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'page-sidebar.php',
			),
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
) );

endif;
